### ISSUE TITLE
How to build this library?

### ISSUE THREAD

**Issue by Nisthar** [woof1001/Shopify-Node-Addons#2]
I am new to compiling node native addons.
I tried `node-gyp build` in a native addon folder.
Its giving me the error:
```
httptest.h(10): fatal error C1083: Cannot open include file: 'cpr/cpr.h': N
o such file or directory
```

**Comment by gchen1295** [comment]
You'll need to compile or download the libraries from online and link it in your compiler in this case in your node-gyp binding.gyp file.

**Comment by Nisthar** [comment]
@woof1001 can you tell me how to do that? I am not very good at c++. 
I can see the dependencies folder but i don't know how to link it to the compiler.

**Comment by Nisthar** [comment]
@woof1001 I added the dependencies in `binding.gyp` like this 
```
'include_dirs': [
            "<!@(node -p \"require('node-addon-api').include\")",
            "D:\\node_projects\\Shopify-Node-Addons\\dependencies\\x64-windows\\include**"
        ],
        'libraries': [
            "D:\\node_projects\\Shopify-Node-Addons\\dependencies\\x64-windows\\lib\\**"
        ],
```
pointing to the lib folder. Its still not working.

**Comment by Nisthar** [comment]
I am able to build it finally using `vcpkg`. Thanks for this library.

**Comment by Nisthar** [comment]
Unrelated to this issue, `Has not been updated for any changes after Anti-bot protection was added` what does this mean?

**Comment by gchen1295** [comment]
There has been a lot of changes made to Shopify since I last wrote the module. You can find out more by running through the requests yourself and just experimenting.

**Comment by Nisthar** [comment]
@woof1001 Do you plan to add the anti bot bypass? The library is great either way though.
